services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/php_error.log:/usr/local/etc/php/php_error.log
    networks:
      - laravel-network
    ports:
      - 9000:9000

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network
    ports:
      - 80:80

networks:
  laravel-network:
    driver: bridge
