services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/php_error.log:/usr/local/etc/php/php_error.log
    networks:
      - laravel-network
    ports:
      - 9000:9000
    depends_on:
      - db
    command: >
      sh -c "composer install --optimize-autoloader; php artisan migrate --force; nohup php artisan queue:work --daemon & php-fpm"

  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    volumes:
      - ./docker/db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-network

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network
    ports:
      - 80:80

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 1234
    networks:
      - laravel-network
    depends_on:
      - db

volumes:
  db_data:

networks:
  laravel-network:
    driver: bridge
